name: 正式版

on:
  push:
    tags:
      - v*
env:
  GITHUB_TOKEN: ${{ github.token }}
  
jobs:
  my-job:
    name: Build docker-natcloud on Push Tag 🚀
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        
      - name: Tidy Go modules
        run: go mod tidy -go=1.17
        
      - name: Build linux-x64
        run: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o artifacts/docker-natcloud-linux-x64
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/docke-*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
        
